### ISSUE TITLE
Set up Imgx as our Digital Asset Manager

### ISSUE THREAD

**Issue by newswim** [open-austin/website-v2#23]
Next has an [`<Image />` component](https://nextjs.org/docs/basic-features/image-optimization) that does some nice things that help with page load times and minimizing the amount of data sent to the client.

I don't think that this component will work for a static site, though.

### Goal

1. See if using a service like [imgx](https://imgix.com) would be worthwhile.
2. Are there issues with using git for asset management? @attali-david has had issues with his branch that contains a lot of images from the old website.

**Comment by attali-david** [comment]
1. Imgx has a lot going for it. Its free tier should be more than sufficient. It automatically optimizes, compresses, resizes, and caches images for faster load times. It has a well-built API and well-written documentation. I don't see much of a downside especially for our limited purposes. 
2. Git is terrible for asset management because it saves every version of an asset. There are extensions for git such Large File Storage that work around git by replacing assets in the tree with pointer files that point to a separate repository that holds all the assets and lazy loads them as necessary. There are a couple of downsides however. The free tier is capped at 1GB, and everyone working on the repository needs to install the LFS extension. I found [this](https://www.atlassian.com/git/tutorials/git-lfs) helpful.

**Comment by newswim** [comment]
Thanks David, yeah it definitely sounds like a combination of using Imgx as our DAM and NextJS's `Image` component should be a good solution here.

**Comment by newswim** [comment]
Notably we'll need to set up a default loader if we use `next/Image`.

https://nextjs.org/docs/basic-features/image-optimization#loaders

Luckily Imgx is already one of the options: https://nextjs.org/docs/api-reference/next/image#built-in-loaders

**Comment by newswim** [comment]
So.. Imgix doesn't actually _host_ the images. You have to use a third party hosting solution. This is kind of.. a bummer.. because we'll have coordinate between multiple services (Imgix and some data hosting service).

There are some alternatives. The fanciest appears to be Cloudinary. They have a [pretty generous free tier](https://cloudinary.com/pricing), and it would probably work for us. But I have some reservations around the credit system.

Another option is to use Imgix and Google Cloud Storage. I'm leaning toward this, but going to look into Cloudinary a bit more.

**Comment by newswim** [comment]
I'm starting to think that maybe we should just use Vercel, with their Hobby tier. There's no additional setup needed to use Next's `Image` component. And they offer image optimization for up to 1000 images for free.

https://vercel.com/pricing

**Comment by lianilychee** [comment]
ended up going with vercel
